stages:
  - preparation
  - testing
  - analysis

image: lorisleiva/laravel-docker:8.1

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: preparation
  before_script:
    - composer config --auth http-basic.vcs.cyberfusion.nl "gitlab-ci-token" "$CI_JOB_TOKEN" --no-ansi --no-interaction
  script:
    - composer --version
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    paths:
      - vendor/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

phpunit:
  stage: testing
  coverage: '/^\s*Lines:\s*(\d+\.\d+)\%/'
  variables:
    XDEBUG_MODE: coverage
  services:
    - name: mariadb:10.6
  dependencies:
    - composer
  script:
    - php -v
    - php -d memory_limit=4G ./vendor/bin/phpunit --coverage-text --colors=never
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

phpstan:
  stage: analysis
  services:
    - name: mariadb:10.6
  dependencies:
    - composer
    - environment
    - build-database
  script:
    - ./vendor/bin/phpstan --version
    - php -d memory_limit=4G ./vendor/bin/phpstan analyse -v --no-ansi --no-interaction
  cache:
    paths:
      - vendor/

pint:
  stage: analysis
  script:
    - ./vendor/bin/pint --test